services:
  yanblog:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3002:80"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./config:/app/config
    restart: always

volumes: {}