FROM nginx:alpine

RUN apk add --no-cache ca-certificates tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

RUN mkdir -p /app/uploads /app/data /app/config /app/web/frontend/public /app/defaults

COPY yanblog_linux_cgo /app/yanblog
COPY config/config_template.yaml /app/config/config.yaml.template
COPY web/frontend/public/config.yaml /app/web/frontend/public/config.yaml
COPY web/frontend/dist /usr/share/nginx/html/
COPY web/backend/dist /usr/share/nginx/html/admin/
COPY uploads/defaults /app/defaults

COPY web/frontend/public/static /app/web/frontend/public/static
COPY web/frontend/public/iconfont /app/web/frontend/public/iconfont
COPY web/frontend/public/favicon.ico /app/web/frontend/public/favicon.ico
COPY web/frontend/public/favicon.svg /app/web/frontend/public/favicon.svg

COPY config/nginx/yanblog.conf /etc/nginx/conf.d/default.conf
COPY config/nginx/nginx.conf /etc/nginx/nginx.conf

COPY config/docker/entry.sh /entry.sh
RUN chmod +x /entry.sh

WORKDIR /app

EXPOSE 80

CMD ["/entry.sh"]